### ISSUE TITLE
functions.php modifications unconditional making child themes difficult to implement

### ISSUE THREAD

**Issue by benwhitehouse** [richardshepherd/TwentyTenFive#13]
The edits to the functions.php file build after of the twentyten base, but as the additions are not conditional, redeclaring them in any child theme creates PHP errors.

Discovered when I tried to edit the _twentyten_posted_on_ tag and received an error because it was being called twice. When I looked in the functions.php files I discovered the  _twentyten_posted_on_ being called conditionally on line 441 and unconditionally on line 561 of the TwentyTen Five theme. The call on line 561 directly conflicts with any call from a child theme.

This is a huge problem if you intend this theme as a starter theme, as child themes are forced to use TwentyTen Five functions rather than their own.

**Comment by richardshepherd** [comment]
Hi Ben - this has now been fixed.
