### ISSUE TITLE
Fatal error: Call to undefined function...

### ISSUE THREAD

**Issue by darronz** [richardshepherd/TwentyTenFive#2]
Hi Richard,

I've installed the theme on a fresh Wordpress 3.0.5 and I get 

Fatal error: Call to undefined function has_post_thumbnail() ~/TwentyTenFive/header.php on line 76

I fixed it in my env by adding add_theme_support( 'post-thumbnails' ); to functions.php

**Comment by richardshepherd** [comment]
I've added this into functions.php, and also merged in the rest of the TwentyTen functions.php file. Hope that helps!
