### ISSUE TITLE
Demo site for Twenty Ten Five

### ISSUE THREAD

**Issue by sankaranand** [richardshepherd/TwentyTenFive#3]
Please Create a demo site of Twenty Ten Five and add the same in official site, so users who download them can be confident of it before.

**Comment by richardshepherd** [comment]
This is a great idea. I'll get onto it asap...

**Comment by sankaranand** [comment]
Thanks for the consideration. Generally users who want to check the performance of HTML5 and see the changes visually and experience the html 5 features would love to see the demo first. :)
